name: 'CI/CD'
on:
  workflow_dispatch:
    inputs:
      branche:
        description: 'Select Branche'
        required: true
        options:
        - 'main'
        default: 'main'

jobs:
  build:
    runs-on: macos-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "us-east-1"
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branche }}

      - name: Cocos Creator Build Use ConfigPath
        uses: lyzz0612/cocos-build@1.0.1
        with:
          config_path: ./web-desktop.json
   
      - name: Configure AWS Credentials 2
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Upload Files To S3 and Cloudfront Create Invalidation
        run: |
          aws s3 sync settings s3://cocos-test.helix.city \
          && aws cloudfront create-invalidation --distribution-id E1E042I8V90ZQT --paths "/*"
       
